theme: jekyll-theme-architect
title: Architect theme
<iframe width="560" height="315" src="https://www.youtube.com/embed/jcCCT570RRc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
Hi.
